-- Mock 平台接单联调用表

CREATE TABLE IF NOT EXISTS `ticket_mock_platform_order` (
  `mock_order_id` bigint NOT NULL COMMENT 'Mock 订单请求主键',
  `tenant_id` varchar(20) DEFAULT '000000' COMMENT '租户编号',
  `platform_code` varchar(64) NOT NULL COMMENT '平台编码',
  `execution_id` bigint DEFAULT NULL COMMENT '执行记录主键',
  `task_id` bigint DEFAULT NULL COMMENT '任务主键',
  `account_id` bigint DEFAULT NULL COMMENT '账号主键',
  `flow_type` varchar(32) DEFAULT NULL COMMENT '下单方式',
  `fulfillment_type` varchar(32) DEFAULT NULL COMMENT '履约方式',
  `payment_mode` varchar(32) DEFAULT NULL COMMENT '支付方式',
  `step_type` varchar(64) DEFAULT NULL COMMENT '当前步骤类型',
  `product_id` varchar(128) DEFAULT NULL COMMENT '商品ID',
  `purchase_quantity` int DEFAULT NULL COMMENT '购买数量',
  `pickup_store_code` varchar(128) DEFAULT NULL COMMENT '自提门店编码',
  `delivery_option` varchar(128) DEFAULT NULL COMMENT '配送方式',
  `request_payload` longtext COMMENT '请求报文(JSON)',
  `response_payload` longtext COMMENT '响应报文(JSON)',
  `mock_status` varchar(32) DEFAULT NULL COMMENT 'Mock 返回状态',
  `mock_order_no` varchar(128) DEFAULT NULL COMMENT 'Mock 订单号',
  `payment_status` varchar(32) DEFAULT NULL COMMENT '支付状态',
  `created_at` datetime DEFAULT NULL COMMENT '接单时间',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `create_by` bigint DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` bigint DEFAULT '0' COMMENT '删除标志',
  PRIMARY KEY (`mock_order_id`),
  KEY `idx_ticket_mock_platform_order_execution` (`execution_id`),
  KEY `idx_ticket_mock_platform_order_task` (`task_id`),
  KEY `idx_ticket_mock_platform_order_platform_step` (`platform_code`, `step_type`),
  KEY `idx_ticket_mock_platform_order_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Mock 平台接单请求记录表';
