CREATE TABLE IF NOT EXISTS `ticket_mail_record` (
  `record_id` bigint(20) NOT NULL COMMENT '邮件记录主键',
  `tenant_id` varchar(20) DEFAULT '000000' COMMENT '租户编号',
  `mailbox_id` bigint(20) NOT NULL COMMENT '邮箱账号主键',
  `account_id` bigint(20) DEFAULT NULL COMMENT '关联平台账号',
  `email` varchar(255) NOT NULL COMMENT '邮箱地址',
  `username` varchar(255) DEFAULT NULL COMMENT '邮箱用户名',
  `folder_name` varchar(128) DEFAULT NULL COMMENT '邮件目录',
  `message_id` varchar(255) DEFAULT NULL COMMENT 'Message-ID',
  `subject` varchar(1000) DEFAULT NULL COMMENT '邮件标题',
  `from_address` varchar(500) DEFAULT NULL COMMENT '发件人',
  `received_at` datetime DEFAULT NULL COMMENT '收件时间',
  `body_excerpt` varchar(2000) DEFAULT NULL COMMENT '正文摘要',
  `body_content` longtext COMMENT '邮件正文',
  `parse_type` varchar(32) DEFAULT NULL COMMENT '解析类型',
  `verify_code` varchar(32) DEFAULT NULL COMMENT '验证码',
  `activation_url` longtext COMMENT '激活链接',
  `parsed` tinyint(1) DEFAULT 0 COMMENT '是否解析成功',
  `read_source` varchar(64) DEFAULT NULL COMMENT '读取来源',
  `sync_time` datetime DEFAULT NULL COMMENT '同步时间',
  `del_flag` bigint(20) DEFAULT 0 COMMENT '删除标志',
  `create_dept` bigint(20) DEFAULT NULL COMMENT '创建部门',
  `create_by` bigint(20) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint(20) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`record_id`),
  UNIQUE KEY `uk_ticket_mail_record_message` (`mailbox_id`, `message_id`, `del_flag`),
  KEY `idx_ticket_mail_record_mailbox` (`mailbox_id`),
  KEY `idx_ticket_mail_record_account` (`account_id`),
  KEY `idx_ticket_mail_record_received` (`received_at`),
  KEY `idx_ticket_mail_record_verify_code` (`verify_code`),
  KEY `idx_ticket_mail_record_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='邮箱邮件记录表';
