CREATE TABLE IF NOT EXISTS `ticket_lottery_event_parse_record` (
  `record_id` bigint NOT NULL COMMENT '解析记录ID',
  `platform_id` bigint NOT NULL COMMENT '平台ID',
  `event_url` varchar(500) NOT NULL COMMENT 'LivePocket 活动链接',
  `ticket_entry_url` varchar(500) DEFAULT NULL COMMENT 'LivePocket tickets页链接',
  `event_title` varchar(300) DEFAULT NULL COMMENT '活动标题',
  `entry_start_time` varchar(32) DEFAULT NULL COMMENT '受付开始时间',
  `entry_end_time` varchar(32) DEFAULT NULL COMMENT '受付结束时间',
  `sessions_json` longtext COMMENT '场次列表JSON',
  `raw_summary` longtext COMMENT '页面摘要',
  `parse_status` varchar(32) DEFAULT 'completed' COMMENT '解析状态',
  `parse_request_id` varchar(64) DEFAULT NULL COMMENT '解析请求ID',
  `parse_message` varchar(500) DEFAULT NULL COMMENT '解析消息',
  `del_flag` bigint NOT NULL DEFAULT 0 COMMENT '删除标志',
  `tenant_id` varchar(20) DEFAULT '000000' COMMENT '租户编号',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `create_by` bigint DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`record_id`),
  UNIQUE KEY `uk_ticket_lottery_parse_record` (`tenant_id`, `platform_id`, `event_url`, `del_flag`),
  KEY `idx_ticket_lottery_parse_platform` (`tenant_id`, `platform_id`, `del_flag`),
  KEY `idx_ticket_lottery_parse_time` (`tenant_id`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='抽票活动解析记录';
